// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qrjTjwHicW_4XbO15ZEOGII8-RGZfgQ',
    appId: '1:689321524516:web:31551049aafc852d1ac7b1',
    messagingSenderId: '689321524516',
    projectId: 'fir-flutter-codelab-34394',
    authDomain: 'fir-flutter-codelab-34394.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-34394.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1W5o031KDxNy8c_uMWkKj3zAsJqJpUg',
    appId: '1:689321524516:android:0a7ea8a21992df5f1ac7b1',
    messagingSenderId: '689321524516',
    projectId: 'fir-flutter-codelab-34394',
    storageBucket: 'fir-flutter-codelab-34394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40qBRC6Fi-XR2Qr5Pf7StJoVMq3hiVu4',
    appId: '1:689321524516:ios:46928459cf72e3531ac7b1',
    messagingSenderId: '689321524516',
    projectId: 'fir-flutter-codelab-34394',
    storageBucket: 'fir-flutter-codelab-34394.appspot.com',
    iosClientId: '689321524516-sj3cbl4b62b6ubm297d9mfbtj0061s5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40qBRC6Fi-XR2Qr5Pf7StJoVMq3hiVu4',
    appId: '1:689321524516:ios:46928459cf72e3531ac7b1',
    messagingSenderId: '689321524516',
    projectId: 'fir-flutter-codelab-34394',
    storageBucket: 'fir-flutter-codelab-34394.appspot.com',
    iosClientId: '689321524516-sj3cbl4b62b6ubm297d9mfbtj0061s5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
